In [2]:

import numpy as np

# 1d array to list
arr = np.array([1, 2, 3])
print(f'NumPy Array:\n{arr}')

list1 = arr.tolist()
print(f'List: {list1}')


NumPy Array:
[1 2 3]
List: [1, 2, 3]


In [6]:
import numpy as np
m = np.arange(6).reshape(2,3)
print(m)
result =  np.trace(m)
print(result)

[[0 1 2]
 [3 4 5]]
4


In [11]:
import numpy as np
x = np.array([[0, 10, 20], [20, 30, 40]])
print(x)
print("Values bigger than 10 =", x[x>10])

[[ 0 10 20]
 [20 30 40]]
Values bigger than 10 = [20 20 30 40]


In [10]:
import numpy as np
a = np.random.rand(3, 4)
print(a)
b = a - a.mean(axis=1, keepdims=True)
print(b)

[[0.89465308 0.57051327 0.19912447 0.66985212]
 [0.79701183 0.57731922 0.02913487 0.29661402]
 [0.67523986 0.58301043 0.08569006 0.36964122]]
[[ 0.31111734 -0.01302247 -0.38441126  0.08631638]
 [ 0.37199185  0.15229924 -0.39588512 -0.12840596]
 [ 0.24684447  0.15461504 -0.34270533 -0.05875417]]
